version: '3'

services:
  app:
    container_name: product-app
    image: 'app.jar'
    restart: always
    build: produto-api
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
    environment:
      - URL_POSTGRES=jdbc:postgresql://db:5432/DB_south
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_RABBITMQ_HOST=rabbitmq

#  producer:
#    container_name: producer-app
#    image: 'producer-app.jar'
#    restart: always
#    build: produto-producer-api
#    ports:
#      - "8081:8081"

  db:
    container_name: db
    image: postgres:13
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=DB_south

  rabbitmq:
    image: rabbitmq:3.7.8-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest


