spring:

  rabbitmq:
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:rabbitmq}
    password: ${RABBITMQ_DEFAULT_PASS:rabbitmq}
    virtual-host: /

security:
  oauth2:
    client:
      scope: password
      client-id: south
      client-secret: 12345

