spring:
  datasource:
    url: ${URL_POSTGRES:jdbc:postgresql://localhost:5435/DB_south}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}


  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: true
