spring:
  profiles:
    active: dev

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: rabbitmq
    password: rabbitmq

security:
  oauth2:
    client:
      scope: password
      client-id: south
      client-secret: 12345

