spring:
  rabbitmq:
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
    virtual-host: /

security:
  oauth2:
    client:
      scope: password
      client-id: south
      client-secret: 12345

