version: "3.5"

services:
  database:
    image: postgres:14-alpine
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=db_south2
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
