version: '2'
services:
  app:
    container_name: app-springboot-south
    image: 'app.jar'
    restart: always
    build: ./
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    environment:
      - POSTGRES_URL_DB=jdbc:postgresql://db:5432/DB_south

  db:
    container_name: db
    image: postgres:13
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=DB_south
