version: '3'

services:
  app:
    container_name: app-springboot-south
    image: 'app.jar'
    restart: always
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_URL_DB=jdbc:postgresql://db:5432/DB_south
      - USER_POSTGRES=postgres
      - PASSWORD_POSTGRES=postgres
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_RABBITMQ_HOST=rabbitmq

  db:
    container_name: db
    image: postgres:13
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=DB_south

  rabbitmq:
    image: rabbitmq:3.7.8-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq