spring:
  datasource:
    url: jdbc:h2:mem:testdb
    name: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
  security:
    user:
      name: vitor
      password: vitor